      Subroutine Type3254

! Object: Variable capacity heat pump
! Simulation Studio Model: Type3254
! 

! Author: 
! Editor: 
! Date:	 May 31, 2018
! last modified: May 31, 2018
! 
! 
! *** 
! *** Model Parameters 
! *** 
!			Control mode	- [1;2]
!			Humidity mode	- [1;2]
!			Logical Unit - cooling mode	- [10;+Inf]
!			Number of indoor dry-bulb temperatures	- [2;+Inf]
!			Number of indoor wet-bulb temperatures	- [2;+Inf]
!			Number of air flow rates	- [2;+Inf]
!			Number of outdoor dry-bulb temperatures	- [2;+Inf]
!			Number of frequencies	- [2;+Inf]
!			Rated cooling capacity	kJ/hr [0.0;+Inf]
!			Rated sensible cooling capacity	kJ/hr [0.0;+Inf]
!			Rated total cooling power	kJ/hr [0.0;+Inf]
!			Rated inlet air flow rate	kg/hr [0.0;+Inf]
!			Rated frequency	1/S [0.0;+Inf]

! *** 
! *** Model Inputs 
! *** 
!			Inlet air temperature	C [-Inf;+Inf]
!			Inlet air humidity ratio	- [0.0;+Inf]
!			Inlet air % RH	% (base 100) [0.0;100.0]
!			Inlet air flow rate	kg/hr [0.0;+Inf]
!			Inlet air pressure	atm [0.0;+Inf]
!			Outside air temperature	C [-Inf;+Inf]
!			Compressor frequency	1/S [0.0;+Inf]
!			Indoor air temperature setpoint	C [-Inf;+Inf]
!			Indoor air temperature measurment	C [-Inf;+Inf]
!			Indoor fan power	kJ/hr [-Inf;+Inf]
!			Outdoor fan power	kJ/hr [-Inf;+Inf]

! *** 
! *** Model Outputs 
! *** 
!			Outlet air temperature	C [-Inf;+Inf]
!			Outlet air humidity ratio	- [0.0;+Inf]
!			Outlet air % RH	% (base 100) [0.0;100]
!			Outlet air flow rate	kg/hr [0.0;+Inf]
!			Outlet air pressure	atm [0.0;+Inf]
!			Total cooling rate	kJ/hr [-Inf;+Inf]
!			Sensible cooling rate	kJ/hr [-Inf;+Inf]
!			Latent cooling rate	kJ/hr [-Inf;+Inf]
!			Heat rejection rate	kJ/hr [-Inf;+Inf]
!			Total power consumption	kJ/hr [-Inf;+Inf]
!			COP	- [0.0;+Inf]
!			EER	- [0.0;+Inf]
!			Indoor fan power	kJ/hr [-Inf;+Inf]
!			Outdoor fan power	kJ/hr [-Inf;+Inf]
!			Compressor power	kJ/hr [-Inf;+Inf]
!			Condensate temperature	C [-Inf;+Inf]
!			Condensate flow rate	kg/hr [0.0;+Inf]
!			Compressor frequency	1/S [0.0;+Inf]

! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Simulation Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type3254

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType


!    PARAMETERS
      DOUBLE PRECISION Control_mode
      DOUBLE PRECISION Humidity_mode
      DOUBLE PRECISION Logical_Unit___cooling_mode
      DOUBLE PRECISION Number_of_indoor_dry_bulb_temperatures
      DOUBLE PRECISION Number_of_indoor_wet_bulb_temperatures
      DOUBLE PRECISION Number_of_air_flow_rates
      DOUBLE PRECISION Number_of_outdoor_dry_bulb_temperatures
      DOUBLE PRECISION Number_of_frequencies
      DOUBLE PRECISION Rated_cooling_capacity
      DOUBLE PRECISION Rated_sensible_cooling_capacity
      DOUBLE PRECISION Rated_total_cooling_power
      DOUBLE PRECISION Rated_inlet_air_flow_rate
      DOUBLE PRECISION Rated_frequency

!    INPUTS
      DOUBLE PRECISION Inlet_air_temperature
      DOUBLE PRECISION Inlet_air_humidity_ratio
      DOUBLE PRECISION Inlet_air___RH
      DOUBLE PRECISION Inlet_air_flow_rate
      DOUBLE PRECISION Inlet_air_pressure
      DOUBLE PRECISION Outside_air_temperature
      DOUBLE PRECISION Compressor_frequency
      DOUBLE PRECISION Indoor_air_temperature_setpoint
      DOUBLE PRECISION Indoor_air_temperature_measurment
      DOUBLE PRECISION Indoor_fan_power
      DOUBLE PRECISION Outdoor_fan_power

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(13)           !The number of parameters that the the model wants
		Call SetNumberofInputs(11)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(0)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(18)                 !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
      Control_mode = getParameterValue(1)
      Humidity_mode = getParameterValue(2)
      Logical_Unit___cooling_mode = getParameterValue(3)
      Number_of_indoor_dry_bulb_temperatures = getParameterValue(4)
      Number_of_indoor_wet_bulb_temperatures = getParameterValue(5)
      Number_of_air_flow_rates = getParameterValue(6)
      Number_of_outdoor_dry_bulb_temperatures = getParameterValue(7)
      Number_of_frequencies = getParameterValue(8)
      Rated_cooling_capacity = getParameterValue(9)
      Rated_sensible_cooling_capacity = getParameterValue(10)
      Rated_total_cooling_power = getParameterValue(11)
      Rated_inlet_air_flow_rate = getParameterValue(12)
      Rated_frequency = getParameterValue(13)


      Inlet_air_temperature = GetInputValue(1)
      Inlet_air_humidity_ratio = GetInputValue(2)
      Inlet_air___RH = GetInputValue(3)
      Inlet_air_flow_rate = GetInputValue(4)
      Inlet_air_pressure = GetInputValue(5)
      Outside_air_temperature = GetInputValue(6)
      Compressor_frequency = GetInputValue(7)
      Indoor_air_temperature_setpoint = GetInputValue(8)
      Indoor_air_temperature_measurment = GetInputValue(9)
      Indoor_fan_power = GetInputValue(10)
      Outdoor_fan_power = GetInputValue(11)

	
   !Check the Parameters for Problems (#,ErrorType,Text)
   !Sample Code: If( PAR1 <= 0.) Call FoundBadParameter(1,'Fatal','The first parameter provided to this model is not acceptable.')

   !Set the Initial Values of the Outputs (#,Value)
		Call SetOutputValue(1, 0) ! Outlet air temperature
		Call SetOutputValue(2, 0) ! Outlet air humidity ratio
		Call SetOutputValue(3, 0) ! Outlet air % RH
		Call SetOutputValue(4, 0) ! Outlet air flow rate
		Call SetOutputValue(5, 0) ! Outlet air pressure
		Call SetOutputValue(6, 0) ! Total cooling rate
		Call SetOutputValue(7, 0) ! Sensible cooling rate
		Call SetOutputValue(8, 0) ! Latent cooling rate
		Call SetOutputValue(9, 0) ! Heat rejection rate
		Call SetOutputValue(10, 0) ! Total power consumption
		Call SetOutputValue(11, 0) ! COP
		Call SetOutputValue(12, 0) ! EER
		Call SetOutputValue(13, 0) ! Indoor fan power
		Call SetOutputValue(14, 0) ! Outdoor fan power
		Call SetOutputValue(15, 0) ! Compressor power
		Call SetOutputValue(16, 0) ! Condensate temperature
		Call SetOutputValue(17, 0) ! Condensate flow rate
		Call SetOutputValue(18, 0) ! Compressor frequency


   !If Needed, Set the Initial Values of the Static Storage Variables (#,Value)
   !Sample Code: SetStaticArrayValue(1,0.d0)

   !If Needed, Set the Initial Values of the Dynamic Storage Variables (#,Value)
   !Sample Code: Call SetDynamicArrayValueThisIteration(1,20.d0)

   !If Needed, Set the Initial Values of the Discrete Controllers (#,Value)
   !Sample Code for Controller 1 Set to Off: Call SetDesiredDiscreteControlState(1,0) 

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      Control_mode = getParameterValue(1)
      Humidity_mode = getParameterValue(2)
      Logical_Unit___cooling_mode = getParameterValue(3)
      Number_of_indoor_dry_bulb_temperatures = getParameterValue(4)
      Number_of_indoor_wet_bulb_temperatures = getParameterValue(5)
      Number_of_air_flow_rates = getParameterValue(6)
      Number_of_outdoor_dry_bulb_temperatures = getParameterValue(7)
      Number_of_frequencies = getParameterValue(8)
      Rated_cooling_capacity = getParameterValue(9)
      Rated_sensible_cooling_capacity = getParameterValue(10)
      Rated_total_cooling_power = getParameterValue(11)
      Rated_inlet_air_flow_rate = getParameterValue(12)
      Rated_frequency = getParameterValue(13)

		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
      Inlet_air_temperature = GetInputValue(1)
      Inlet_air_humidity_ratio = GetInputValue(2)
      Inlet_air___RH = GetInputValue(3)
      Inlet_air_flow_rate = GetInputValue(4)
      Inlet_air_pressure = GetInputValue(5)
      Outside_air_temperature = GetInputValue(6)
      Compressor_frequency = GetInputValue(7)
      Indoor_air_temperature_setpoint = GetInputValue(8)
      Indoor_air_temperature_measurment = GetInputValue(9)
      Indoor_fan_power = GetInputValue(10)
      Outdoor_fan_power = GetInputValue(11)
		

	!Check the Inputs for Problems (#,ErrorType,Text)
	!Sample Code: If( IN1 <= 0.) Call FoundBadInput(1,'Fatal','The first input provided to this model is not acceptable.')
 
      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Previous Control States if Discrete Controllers are Being Used (#)
	!Sample Code: CONTROL_LAST=getPreviousControlState(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Values from the Global Storage Array for the Static Variables (#)
	!Sample Code: STATIC1=getStaticArrayValue(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Initial Values of the Dynamic Variables from the Global Storage Array (#)
	!Sample Code: T_INITIAL_1=getDynamicArrayValueLastTimestep(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!Perform All of the Calculations Here to Set the Outputs from the Model Based on the Inputs

	!Sample Code: OUT1=IN1+PAR1

	!If the model requires the solution of numerical derivatives, set these derivatives and get the current solution
	!Sample Code: T1=getNumericalSolution(1)
	!Sample Code: T2=getNumericalSolution(2)
	!Sample Code: DTDT1=3.*T2+7.*T1-15.
	!Sample Code: DTDT2=-2.*T1+11.*T2+21.
	!Sample Code: Call SetNumericalDerivative(1,DTDT1)
	!Sample Code: Call SetNumericalDerivative(2,DTDT2)

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)
		Call SetOutputValue(1, 0) ! Outlet air temperature
		Call SetOutputValue(2, 0) ! Outlet air humidity ratio
		Call SetOutputValue(3, 0) ! Outlet air % RH
		Call SetOutputValue(4, 0) ! Outlet air flow rate
		Call SetOutputValue(5, 0) ! Outlet air pressure
		Call SetOutputValue(6, 0) ! Total cooling rate
		Call SetOutputValue(7, 0) ! Sensible cooling rate
		Call SetOutputValue(8, 0) ! Latent cooling rate
		Call SetOutputValue(9, 0) ! Heat rejection rate
		Call SetOutputValue(10, 0) ! Total power consumption
		Call SetOutputValue(11, 0) ! COP
		Call SetOutputValue(12, 0) ! EER
		Call SetOutputValue(13, 0) ! Indoor fan power
		Call SetOutputValue(14, 0) ! Outdoor fan power
		Call SetOutputValue(15, 0) ! Compressor power
		Call SetOutputValue(16, 0) ! Condensate temperature
		Call SetOutputValue(17, 0) ! Condensate flow rate
		Call SetOutputValue(18, 0) ! Compressor frequency

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Desired Disceret Control Signal Values for this Iteration (#,State)
!Sample Code:  Call SetDesiredDiscreteControlState(1,1)
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Final value of the Dynamic Variables in the Global Storage Array (#,Value)
!Sample Code:  Call SetDynamicArrayValueThisIteration(1,T_FINAL_1)
!-----------------------------------------------------------------------------------------------------------------------
 
      Return
      End
!-----------------------------------------------------------------------------------------------------------------------

